deepbrook_portfolio/urls.py
from django.urls import path
from . import views

app_name="deepbrook_portfolio"
urlpatterns = [
        path("", views.index, name="index"),
        path("login", views.login, name="login"),
        path("register", views.register, name="register"),
        path("portfolio", views.portfolio, name="portfolio"),
        path("qoute", views.quote, name="quote"),
        path("buy", views.buy, name="buy"),
        path("sell", views.sell, name="sell"),
        path("history", views.history, name="history")
    ]

finance_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('deepbrook_portfolio/', include("deepbrook_portfolio.urls"))
]

deepbrook_portfolio/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass

deepbrook_portfolio/forms.py
from django import forms

class NewUserForm(forms.Form):
    username = forms.CharField(label="declare username")
    password_declare = forms.CharField(label="declare password")
    password_confirm = forms.CharField(label="confirm password")

class LoginForm(forms.Form):
    username = forms.CharField(label="username")
    password = forms.CharField(label="password")
    
    def clean_message(self):
        username = self.cleaned_data.get("username")
        return username

deepbrook_portfolio/views.py
from django.db import IntegrityError
from django.shortcuts import render
from deepbrook_portfolio.forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .models import User

def index(request):
    return render(request, "deepbrook_portfolio/index.html")

def about(request):
    return render(request, "deepbrook_portfolio/about.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return render(request, "deepbrook_portfolio/index.html")
        else:
            return render(request, "deepbrook_portfolio/login.html", {
                "message": "Invalid login credentials. Try again:"
            })
    else:
        return render(request, "deepbrook_portfolio/login.html", {
            "message": "Log In"
        })

def logout_view(request):
    logout(request)
    return render(request, "deepbrook_portfolio/loggedout.html")

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]

        if password != confirmation:
            return render(request, "deepbrook_portfolio/register.html", {
                "message": "Passwords do not match"
            })

        try:
            email = None
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "deepbrook_portfolio/register.html", {
                "message": "Username unavailable"
            })
        login(request, user)
        return render(request, "deepbrook_portfolio/index.html")
    else:
        return render(request, "deepbrook_portfolio/register.html")


@login_required
def portfolio(request):
    return render(request, "deepbrook_portfolio/portfolio.html")

@login_required
def quote(request):
    if request.method == "POST":
        ticker = request.POST["ticker"]
        return display_quote(request, ticker)
    else:
        return render(request, "deepbrook_portfolio/quote.html")

@login_required
def display_quote(request, ticker):
    base = "https://cloud.iexapis.com/"
    version = "stable/"
    endpoint = "stock/{ticker}/quote?".format(ticker=ticker)
    token = "token=pk_fdde9d37aef44d21a32ae6d070a3ac5d"
    quote_url = "{base}{version}{endpoint}{token}".format(base=base, version=version, endpoint=endpoint, token=token)
    return render(request, "deepbrook_portfolio/display_quote.html", {
        "ticker":ticker.upper(),
        "quote_url": quote_url
    })

@login_required
def buy(request):
    return render(request, "deepbrook_portfolio/buy.html")

@login_required
def sell(request):
    return render(request, "deepbrook_portfolio/sell.html")

@login_required
def history(request):
    return render(request, "deepbrook_portfolio/history.html")

deepbrook_portfolio/templates/deepbrook_portfolio/about.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    Deepbrook Portfolio
{% endblock %}

{% block main %}
	<p>
		Deepbrook Portfolio is a tool to simulate buying and selling stocks.
	</p>

	<p>
		No real money is used, but stock prices shown in the app reflect actual prices, accurate to 15 minutes. Data is provided by IEX Cloud.
	</p>

	<p>
		Users can register for an account my creating a username and password. Once signed in, users start with $10,000 in play money. Get price quotes, buy, sell, view your trade history, and watch what happens to the value of your portfolio as the markets move in real life.
	</p>
{% endblock %}

deepbrook_portfolio/templates/deepbrook_portfolio/buy.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    Buy
{% endblock %}

{% block main %}
    <div class="right">
        <p>Logged in as <span style="color: #7efcd6">{{ request.user.username }}</span></p>
    </div>
    <h5 style="color: white">Buy</h5>
    <form action="/buy" method="post">
        <div class="form-group">
            <input class="form-control" name="symbol" placeholder="ticker symbol" type="text">
        </div>
        <div class="form-group">
            <input class="form-control" name="shares" placeholder="how many shares?" type="text">
        </div>
        <button class="btn btn-primary" type="submit">Place Order</button>
    </form>
{% endblock %}

deepbrook_portfolio/templates/deepbrook_portfolio/display_quote.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    Display Quote
{% endblock %}

{% block main %}
    <div class="right">
        <p>Logged in as <span>{{ request.user.username }}</span></p>
    </div>
	<script>
		document.addEventListener('DOMContentLoaded', function() {
    // Send a GET request to the URL
    fetch('{{ quote_url }}')
    // Put response into json form
    .then(response => response.json())
    .then(data => {

        // Get rate from data
        const price = data.latestPrice;

        // Display message on the screen
        document.querySelector('h4').innerHTML = `$${price}`;
    });
});
	</script>
	<body>
	<h5>Your {{ ticker }} quote, as requested:</h5>
	<h4></h4>
	</body>
{% endblock %} 

deepbrook_portfolio/templates/deepbrook_portfolio/history.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    History
{% endblock %}

{% block main %}
    <div class="right">
        <p>Logged in as <span style="color: #7efcd6">{{ request.user.username }}</span></p>
    </div>
    <h5 style="color: white">History</h5>
    <div class="table-responsive">
        <table class="table" id="portfolio">
            <tr>
                <th><span style="color: #7efcd6">Stock</span></th>
                <th><span style="color: #7efcd6">Order Type</span></th>
                <th><span style="color: #7efcd6">Shares Traded</span></th>
                <th><span style="color: #7efcd6">Trade Price</span></th>
                <th><span style="color: #7efcd6">Timestamp (UTC)</span></th>
            </tr>
        </table>
    </div>
{% endblock %}

deepbrook_portfolio/templates/deepbrook_portfolio/index.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    Deepbrook Portfolio
{% endblock %}

{% block main %}
	{% if user.is_authenticated %}
		<p>
			Hello {{ request.user.username }}, welcome to Deepbrook Portfolio
		</p>
	{% else %}
		<h5>Welcome to Deepbrook Portfolio</h5>
		<p>
			Simulate buying and selling stocks at real-time prices. Experiment with portfolio management.
		</p>
		<p>
			<a href="{% url 'deepbrook_portfolio:login' %}">Log In</a>
		</p>
		<p>
			Don't have an account? <a href="{% url 'deepbrook_portfolio:register' %}">Register</a>
		</p>
	{% endif %}
{% endblock %}

deepbrook_portfolio/templates/deepbrook_portfolio/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- documentation at http://getbootstrap.com/docs/4.1/ -->
		<!-- alternative themes at https://bootswatch.com/ -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
		
		<!-- django-specific syntax link to stylesheet -->
		<link rel="stylesheet" href="{% static 'deepbrook_portfolio/styles.css' %}">

		<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

        <title>Deepbrook Portfolio: {% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light border">
            <a class="navbar-brand" href="{% url 'deepbrook_portfolio:index' %}">
				<span class="blue">Deepbrook Portfolio</span>
			</a>
            <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbar" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
				<ul class="navbar-nav mr-auto mt-2">
					{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'deepbrook_portfolio:portfolio' %}">Portfolio</a>
						</li>
						
						<li class="nav-item">
							<a class="nav-link" href="{% url 'deepbrook_portfolio:quote' %}">Quote</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'deepbrook_portfolio:buy' %}">Buy</a>
						</li>
						
						<li class="nav-item">
							<a class="nav-link" href="{% url 'deepbrook_portfolio:sell' %}">Sell</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'deepbrook_portfolio:history' %}">History</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'deepbrook_portfolio:logout' %}">Log Out</a>
						</li>
					{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'deepbrook_portfolio:about' %}">About</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'deepbrook_portfolio:login' %}">Login</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{% url 'deepbrook_portfolio:register' %}">Register</a>
						</li>
					{% endif %}
				</ul>
            </div>
        </nav>

        <main class="container p-5">
            {% block main %}
			{% endblock %}
        </main>

        <footer class="small text-center text-muted">
            Data provided for free by <a href="https://iextrading.com/developer">IEX</a>. View <a href="https://iextrading.com/api-exhibit-a/">IEX’s Terms of Use</a>.
        </footer>

    </body>

</html>

deepbrook_portfolio/templates/deepbrook_portfolio/loggedout.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    Deepbrook Portfolio
{% endblock %}

{% block main %}
	<h5>Deepbrook Portfolio</h5>
	<p>
		You have been logged out successfuly.
	</p>
	<p>
		<a href="{% url 'deepbrook_portfolio:login' %}">Log In</a>
	</p>
{% endblock %}

deepbrook_portfolio/templates/deepbrook_portfolio/login.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    Log In
{% endblock %}

{% block main %}
<p>{{ message }}</p>
	<form action="{% url 'deepbrook_portfolio:login' %}" method="post">
		{% csrf_token %}
        <div class="form-group">
			<input type="text", name="username", placeholder="Username",
			 		autocomplete="off", autofocus class="form-control">
        </div>
        <div class="form-group">
			<input type="password", name="password", placeholder="Password",
			 		autocomplete="off", class="form-control">
        </div>
        <button class="btn btn-primary" type="submit">Log In</button>
    </form>
	<p>Don't have an account?<a href="{% url 'deepbrook_portfolio:register' %}"> Create new account</a>.</p>
{% endblock %}

deepbrook_portfolio/templates/deepbrook_portfolio/portfolio.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
	Deepbrook Portfolio
{% endblock %}

{% block main %}
    <div class="right">
        <p>Logged in as <span style="color: #7efcd6">{{ request.user.username }}</span></p>
    </div>
    <h5 style="color: white">Deepbrook Portfolio:&nbsp; Portfolio</h5>
    <div class="table-responsive">
        <table class="table" id="portfolio">
            <tr>
                <th><span style="color: #7efcd6">Stock</span></th>
                <th><span style="color: #7efcd6">Shares Owned</span></th>
                <th><span style="color: #7efcd6">Current Price</span></th>
                <th><span style="color: #7efcd6">POSITION VALUE</span></th>
            </tr>
        </table>
        <table id="portfolio" style="width: 50%; margin-right: 0px; margin-left: auto">
            <tr>
                <th><span style="color: #7efcd6">PORTFOLIO VALUE:</span></th>
                <th>&nbsp;{{ portfolio_value }}</th>
            </tr>
            <tr>
                <th><span style="color: #7efcd6">CASH BALANCE:</span></th>
                <th>&nbsp;{{ cash }}</th>
            </tr>
            <tr>
                <th><span style="color: #7efcd6">TOTAL ASSETS:</span></th>
                <th>&nbsp;{{ total_assets }}</th>
            </tr>
        </table>
    </div>
{% endblock %}

deepbrook_portfolio/templates/deepbrook_portfolio/quote.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    Quote
{% endblock %}

{% block main %}
    <div class="right">
        <p>Logged in as <span style="color: #7efcd6">{{ request.user.username }}</span></p>
    </div>
    <h5 style="color: white">Quote</h5>
    <form action="/quote" method="post">
        <div class="form-group">
            <input class="form-control" name="symbol" placeholder="enter ticker symbol" type="text">
        </div>
        <button class="btn btn-primary" type="submit">Quote</button>
    </form>
{% endblock %}

deepbrook_portfolio/templates/deepbrook_portfolio/register.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    Register
{% endblock %}

{% block main %}
    <h4>New Account</h4>
	<p> {{ message }} </p>
	<form action="{% url 'deepbrook_portfolio:register' %}" method="post">
		{% csrf_token %}
        <div class="form-group">
            <input autocomplete="off" autofocus class="form-control" name="username" placeholder="declare username" type="text">
        </div>
        <div class="form-group">
            <input class="form-control" name="password" placeholder="declare password" type="password">
        </div>
        <div class="form-group">
            <input class="form-control" name="confirmation" placeholder="re-type password" type="password">
        </div>
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
{% endblock %}

deepbrook_portfolio/templates/deepbrook_portfolio/sell.html
{% extends "deepbrook_portfolio/layout.html" %}

{% block title %}
    Sell
{% endblock %}

{% block main %}
    <div class="right">
        <p>Logged in as <span style="color: #7efcd6">{{ request.user.username }}</span></p>
    </div>
    <h5 style="color: white">Sell</h5>
    <form action="/sell" method="post">
        <div class="form-group">
            <input class="form-control" name="symbol" placeholder="ticker symbol" type="text">
        </div>
        <div class="form-group">
            <input class="form-control" name="shares" placeholder="how many shares?" type="text">
        </div>
        <button class="btn btn-primary" type="submit">Place Order</button>
    </form>
{% endblock %}